version = 0.1

[default.deploy.parameters]
stack_name = "login"
resolve_s3 = true
s3_prefix = "login"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ICAALogin=197461532156.dkr.ecr.us-east-1.amazonaws.com/logind56b6998/icaalogina6e895derepo"]
