//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	IcaaBearerAuthScopes        = "icaaBearerAuth.Scopes"
	IcaaCookieAuthScopes        = "icaaCookieAuth.Scopes"
	IcaaRefreshCookieAuthScopes = "icaaRefreshCookieAuth.Scopes"
)

// Defines values for AccessTokenTokenType.
const (
	Bearer AccessTokenTokenType = "Bearer"
)

// Defines values for ErrorCode.
const (
	AuthError            ErrorCode = "AuthError"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	RateLimited          ErrorCode = "RateLimited"
)

// Defines values for JWKAlg.
const (
	RS256 JWKAlg = "RS256"
)

// Defines values for JWKKty.
const (
	RSA JWKKty = "RSA"
)

// Defines values for JWKUse.
const (
	Sig JWKUse = "sig"
)

// Defines values for UserInfoRoles.
const (
	ADMIN UserInfoRoles = "ADMIN"
)

// AccessToken A short-lived machine JWT, plus its metadata.
type AccessToken struct {
	// AccessToken The RS256 machine JWT (Bearer).
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds (300 = 5 minutes).
	ExpiresIn int                  `json:"expires_in"`
	TokenType AccessTokenTokenType `json:"token_type"`
}

// AccessTokenTokenType defines model for AccessToken.TokenType.
type AccessTokenTokenType string

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// JWK RSA public key (RFC 7517), kid namespaced machine-* (service tokens) or user-* (user tokens).
type JWK struct {
	Alg *JWKAlg `json:"alg,omitempty"`

	// E Base64url-encoded RSA public exponent.
	E   string `json:"e"`
	Kid string `json:"kid"`
	Kty JWKKty `json:"kty"`

	// N Base64url-encoded RSA modulus.
	N string `json:"n"`

	// Use Key use - signing.
	Use *JWKUse `json:"use,omitempty"`
}

// JWKAlg defines model for JWK.Alg.
type JWKAlg string

// JWKKty defines model for JWK.Kty.
type JWKKty string

// JWKUse Key use - signing.
type JWKUse string

// JWKS JSON Web Key Set (RFC 7517) of ICAA token verification keys.
type JWKS struct {
	Keys []JWK `json:"keys"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	ExpiresAt     time.Time `json:"expiresAt"`
	ProfilePicURL string    `json:"profilePicURL"`

	// Roles User's assigned roles
	Roles     []UserInfoRoles `json:"roles"`
	UserEmail string          `json:"userEmail"`
}

// UserInfoRoles defines model for UserInfo.Roles.
type UserInfoRoles string

// PostLoginGoogleJSONBody defines parameters for PostLoginGoogle.
type PostLoginGoogleJSONBody struct {
	GoogleJWT string `json:"googleJWT"`
}

// PostLoginV1M2mTokensParams defines parameters for PostLoginV1M2mTokens.
type PostLoginV1M2mTokensParams struct {
	// Authorization HTTP Basic credentials - base64(clientId:clientSecret).
	Authorization string `json:"Authorization"`
}

// PostLoginGoogleJSONRequestBody defines body for PostLoginGoogle for application/json ContentType.
type PostLoginGoogleJSONRequestBody PostLoginGoogleJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns the JSON Web Key Set for ICAA token verification
	// (GET /login/.well-known/jwks.json)
	GetLoginWellKnownJwksJson(w http.ResponseWriter, r *http.Request)
	// Logs in and returns the auth cookie
	// (POST /login/google)
	PostLoginGoogle(w http.ResponseWriter, r *http.Request)
	// Refreshes the access token using a refresh token
	// (POST /login/refresh)
	PostLoginRefresh(w http.ResponseWriter, r *http.Request)
	// Logs the user out
	// (DELETE /login/session)
	DeleteLoginSession(w http.ResponseWriter, r *http.Request)
	// Returns info about the current session/user
	// (GET /login/session)
	GetLoginSession(w http.ResponseWriter, r *http.Request)
	// Exchanges machine client credentials for a short-lived JWT
	// (POST /login/v1/m2m-tokens)
	PostLoginV1M2mTokens(w http.ResponseWriter, r *http.Request, params PostLoginV1M2mTokensParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLoginWellKnownJwksJson operation middleware
func (siw *ServerInterfaceWrapper) GetLoginWellKnownJwksJson(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLoginWellKnownJwksJson(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLoginGoogle operation middleware
func (siw *ServerInterfaceWrapper) PostLoginGoogle(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLoginGoogle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLoginRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostLoginRefresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaRefreshCookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLoginRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLoginSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteLoginSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, IcaaRefreshCookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLoginSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLoginSession operation middleware
func (siw *ServerInterfaceWrapper) GetLoginSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLoginSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLoginV1M2mTokens operation middleware
func (siw *ServerInterfaceWrapper) PostLoginV1M2mTokens(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostLoginV1M2mTokensParams

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err := fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLoginV1M2mTokens(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/login/.well-known/jwks.json", wrapper.GetLoginWellKnownJwksJson)
	m.HandleFunc("POST "+options.BaseURL+"/login/google", wrapper.PostLoginGoogle)
	m.HandleFunc("POST "+options.BaseURL+"/login/refresh", wrapper.PostLoginRefresh)
	m.HandleFunc("DELETE "+options.BaseURL+"/login/session", wrapper.DeleteLoginSession)
	m.HandleFunc("GET "+options.BaseURL+"/login/session", wrapper.GetLoginSession)
	m.HandleFunc("POST "+options.BaseURL+"/login/v1/m2m-tokens", wrapper.PostLoginV1M2mTokens)

	return m
}

type GetLoginWellKnownJwksJsonRequestObject struct {
}

type GetLoginWellKnownJwksJsonResponseObject interface {
	VisitGetLoginWellKnownJwksJsonResponse(w http.ResponseWriter) error
}

type GetLoginWellKnownJwksJson200ResponseHeaders struct {
	CacheControl string
}

type GetLoginWellKnownJwksJson200JSONResponse struct {
	Body    JWKS
	Headers GetLoginWellKnownJwksJson200ResponseHeaders
}

func (response GetLoginWellKnownJwksJson200JSONResponse) VisitGetLoginWellKnownJwksJsonResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetLoginWellKnownJwksJson500JSONResponse Error

func (response GetLoginWellKnownJwksJson500JSONResponse) VisitGetLoginWellKnownJwksJsonResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginGoogleRequestObject struct {
	Body *PostLoginGoogleJSONRequestBody
}

type PostLoginGoogleResponseObject interface {
	VisitPostLoginGoogleResponse(w http.ResponseWriter) error
}

type PostLoginGoogle200ResponseHeaders struct {
	SetCookie []string
}

type PostLoginGoogle200JSONResponse struct {
	Body    UserInfo
	Headers PostLoginGoogle200ResponseHeaders
}

func (response PostLoginGoogle200JSONResponse) VisitPostLoginGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	for _, cookie := range response.Headers.SetCookie {
		w.Header().Add("Set-Cookie", cookie)
	}

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostLoginGoogle401JSONResponse Error

func (response PostLoginGoogle401JSONResponse) VisitPostLoginGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginRefreshRequestObject struct {
}

type PostLoginRefreshResponseObject interface {
	VisitPostLoginRefreshResponse(w http.ResponseWriter) error
}

type PostLoginRefresh200ResponseHeaders struct {
	SetCookie []string
}

type PostLoginRefresh200JSONResponse struct {
	Body    UserInfo
	Headers PostLoginRefresh200ResponseHeaders
}

func (response PostLoginRefresh200JSONResponse) VisitPostLoginRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	for _, cookie := range response.Headers.SetCookie {
		w.Header().Add("Set-Cookie", cookie)
	}

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostLoginRefresh401JSONResponse Error

func (response PostLoginRefresh401JSONResponse) VisitPostLoginRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteLoginSessionRequestObject struct {
}

type DeleteLoginSessionResponseObject interface {
	VisitDeleteLoginSessionResponse(w http.ResponseWriter) error
}

type DeleteLoginSession200ResponseHeaders struct {
	SetCookie []string
}

type DeleteLoginSession200Response struct {
	Headers DeleteLoginSession200ResponseHeaders
}

func (response DeleteLoginSession200Response) VisitDeleteLoginSessionResponse(w http.ResponseWriter) error {

	for _, cookie := range response.Headers.SetCookie {
		w.Header().Add("Set-Cookie", cookie)
	}

	w.WriteHeader(200)
	return nil
}

type GetLoginSessionRequestObject struct {
}

type GetLoginSessionResponseObject interface {
	VisitGetLoginSessionResponse(w http.ResponseWriter) error
}

type GetLoginSession200JSONResponse UserInfo

func (response GetLoginSession200JSONResponse) VisitGetLoginSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLoginSession401JSONResponse Error

func (response GetLoginSession401JSONResponse) VisitGetLoginSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginV1M2mTokensRequestObject struct {
	Params PostLoginV1M2mTokensParams
}

type PostLoginV1M2mTokensResponseObject interface {
	VisitPostLoginV1M2mTokensResponse(w http.ResponseWriter) error
}

type PostLoginV1M2mTokens200JSONResponse AccessToken

func (response PostLoginV1M2mTokens200JSONResponse) VisitPostLoginV1M2mTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginV1M2mTokens400JSONResponse Error

func (response PostLoginV1M2mTokens400JSONResponse) VisitPostLoginV1M2mTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginV1M2mTokens401JSONResponse Error

func (response PostLoginV1M2mTokens401JSONResponse) VisitPostLoginV1M2mTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginV1M2mTokens429JSONResponse Error

func (response PostLoginV1M2mTokens429JSONResponse) VisitPostLoginV1M2mTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginV1M2mTokens500JSONResponse Error

func (response PostLoginV1M2mTokens500JSONResponse) VisitPostLoginV1M2mTokensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Returns the JSON Web Key Set for ICAA token verification
	// (GET /login/.well-known/jwks.json)
	GetLoginWellKnownJwksJson(ctx context.Context, request GetLoginWellKnownJwksJsonRequestObject) (GetLoginWellKnownJwksJsonResponseObject, error)
	// Logs in and returns the auth cookie
	// (POST /login/google)
	PostLoginGoogle(ctx context.Context, request PostLoginGoogleRequestObject) (PostLoginGoogleResponseObject, error)
	// Refreshes the access token using a refresh token
	// (POST /login/refresh)
	PostLoginRefresh(ctx context.Context, request PostLoginRefreshRequestObject) (PostLoginRefreshResponseObject, error)
	// Logs the user out
	// (DELETE /login/session)
	DeleteLoginSession(ctx context.Context, request DeleteLoginSessionRequestObject) (DeleteLoginSessionResponseObject, error)
	// Returns info about the current session/user
	// (GET /login/session)
	GetLoginSession(ctx context.Context, request GetLoginSessionRequestObject) (GetLoginSessionResponseObject, error)
	// Exchanges machine client credentials for a short-lived JWT
	// (POST /login/v1/m2m-tokens)
	PostLoginV1M2mTokens(ctx context.Context, request PostLoginV1M2mTokensRequestObject) (PostLoginV1M2mTokensResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLoginWellKnownJwksJson operation middleware
func (sh *strictHandler) GetLoginWellKnownJwksJson(w http.ResponseWriter, r *http.Request) {
	var request GetLoginWellKnownJwksJsonRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLoginWellKnownJwksJson(ctx, request.(GetLoginWellKnownJwksJsonRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLoginWellKnownJwksJson")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLoginWellKnownJwksJsonResponseObject); ok {
		if err := validResponse.VisitGetLoginWellKnownJwksJsonResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLoginGoogle operation middleware
func (sh *strictHandler) PostLoginGoogle(w http.ResponseWriter, r *http.Request) {
	var request PostLoginGoogleRequestObject

	var body PostLoginGoogleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLoginGoogle(ctx, request.(PostLoginGoogleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLoginGoogle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLoginGoogleResponseObject); ok {
		if err := validResponse.VisitPostLoginGoogleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLoginRefresh operation middleware
func (sh *strictHandler) PostLoginRefresh(w http.ResponseWriter, r *http.Request) {
	var request PostLoginRefreshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLoginRefresh(ctx, request.(PostLoginRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLoginRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLoginRefreshResponseObject); ok {
		if err := validResponse.VisitPostLoginRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteLoginSession operation middleware
func (sh *strictHandler) DeleteLoginSession(w http.ResponseWriter, r *http.Request) {
	var request DeleteLoginSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteLoginSession(ctx, request.(DeleteLoginSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteLoginSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteLoginSessionResponseObject); ok {
		if err := validResponse.VisitDeleteLoginSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLoginSession operation middleware
func (sh *strictHandler) GetLoginSession(w http.ResponseWriter, r *http.Request) {
	var request GetLoginSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLoginSession(ctx, request.(GetLoginSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLoginSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLoginSessionResponseObject); ok {
		if err := validResponse.VisitGetLoginSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLoginV1M2mTokens operation middleware
func (sh *strictHandler) PostLoginV1M2mTokens(w http.ResponseWriter, r *http.Request, params PostLoginV1M2mTokensParams) {
	var request PostLoginV1M2mTokensRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLoginV1M2mTokens(ctx, request.(PostLoginV1M2mTokensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLoginV1M2mTokens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLoginV1M2mTokensResponseObject); ok {
		if err := validResponse.VisitPostLoginV1M2mTokensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZWXPbOBL+K13YrVp5izrsHFOjlB8Ux5n4SOKynPFDJuXAZItCDAJcALSsTem/bzVA",
	"SqRI28nuJlPzJAlHo6/v6wb0lcU6y7VC5Swbf2U2nmPG/ddJHKO1F/oGFf1M0MZG5E5oxcZsAnaujetL",
	"cYsJZDyeC4VwfHkRQS4LC8JZyNDxhDs+YBHLjc7ROIFeNPeir1y37Is5wvl079nzulzovURu0OyQNLfM",
	"kY2ZdUaolK0ihne5MGivRJc4OgWkmKETGYJQYDHWKrHQezIawT48g0yowqH1svGOZ7lENn4yGq1PEsph",
	"ioaO8kpfhfGvDFWRsfFHFpRjn1q6rSJm8F+FMJjQuoblDWENIzZy9PUXjB0dfGiMNnRm05exTrwmfzc4",
	"Y2P2t+EmoMMymkO/9YAWriKWobU8DdpXtrKJgkLhXY6xwwSQ1oOO48IYTAbsMau8DhvJ92p/oJOG146U",
	"Q6O49JMsYpPCzavvRyov3O9cioRTIKvhc+7wVGTCYdLh7YgdX560U+B8OoG8uJYihhtcQu/89QH88mz3",
	"l50IbkQCimdocx5vMrn/T+hZNLciRvAxsjugDRQWDU3RZzXekd0yrRvpU7lTV2xr+pJbfP60MLKPirya",
	"QE13vAuB7YTAjUiaIa1MGe12LnfLppKTThXVt6qY6aSQhe1UrbAdlp7gkvwJfbAiVUKltLVSx4r0cSyR",
	"CcFu0pPc2ZV4x5cn0/bpx9P37+ASr4HUmKKr5QToGRwdTCYhwHCLRsxE7JOQsse2A06j9CkcZvYxLFKC",
	"rtZ6cmP4sm0ZCewy5oNFc6Rmuk0DJXlMHP2YaZNxx8Ys4Q77RHtdYcmNngmJZyL+cH5K21orjJZo284j",
	"Lf5hgVuKHCYQlkUb+6swTl69PXrXmVdN832KmMOMC9mhx5ZzmmpHNcvrYirl215cRcxiXBjhllOKSbBQ",
	"xJwHEicSopFr/+t15crjywsWbTnCp0mg9DJbhALar434d8iYOfIEDYtCZSU9gtxNQObO5eQC0uBA6xuB",
	"lQaPHRb71eR4ml//Ijor119NDg4Op9Ori/cnh+82R/JcnOCyOvQcZwbt/NGzTVjXOBx6M11S4XoeVZJr",
	"odzOg5qdH74+P5y+uU81CpMoM32r9VAwOTsCOlfqNBUqBaGc9pj19COcrE6BU50KxSJ2i8aG7buD0WBE",
	"puscFc8FG7MnfihiOXdznwxDSduGgwVK2b9ReqGGXxY3dvDFak+IKbq2XlM0t2jBzbHO2QTlDbnA8eUJ",
	"0c0OUV8CTgd6WQbCOb68sBHtwASul7409TYFiQxu1qSoKkizsjata9IfZDPRg0/Co4SN2W/ovDMuUcoT",
	"Mul4cWOPySCCl821sgEJe6MR832Fcqi8nTzPZcmAw8oFgc6+geymIZZb9Ht5AhYJsQEf/uADHs+xf6CV",
	"M1q2/eun+bVEb+66aYuAS6kXYB2XCAYLGxZwBXNdmAGLarpuqmMITwQZv+vzFPep2wsy+ou5kNg3eBua",
	"D9x/8nw06uiByKxn/0dnhRanw1uvuZAhW6TmSVUvfWo16IyNP36KmC2yjJsltT3oCqNCSrYKHvnonjLn",
	"hZYYSLVOpS/fubbewGZanWkb8uq3sDBwNVr3UifL73JNs56Fc4l0Hy0Im6UdZL+KOm4XQVd/rfBOJQaB",
	"hXBzVpfsTIGrHwiOdTHv0JJoGGzh2X5WyAGQ2iX5c5U0udgCN5T6FG1MyJbAuNZ3tgl8bpWCz17I5zYR",
	"fw7UUUPlFF0/lIbum1ooS4UrdamOvg93LVX2/yhGoydx/WLkR/AFnHE33x++gDfO5e+VXEbQVrjcXvrj",
	"4f33YPjpaPfHY/iD4mVfQBeqh1B7qlNLMQxh3iDY+7gspTWAlpbXEdrq1oKAzvrtNKSoCNEIHBQuGi1G",
	"yDsttxIOBGlY8WPiVQ2btUI/aW2BCfTCaqOd92VnXVoTSNmGsD8JcReNHmYDvW9Hw7uN81oQ/W9hoXBx",
	"9T9Cg0T8peAB/Sq56M4d2vstd24D6Ot9jezHT6utkuiXlIhodNOFpaLKOw4qkWbRhh6SAi/RdaTAKz8e",
	"hFccHHLhVt90wnAxJzg5W+FRWMgNWlQOkwhwNsPYiVuUy3WzSzJ8s6cLN2jBKWjgATUt9e0GVPtK50/A",
	"hOR+RwlAKYNd10YvQg8KwT11L3x73m/y8i2/609S3B+96MzuroWdKdyVKls5En1zAnl2roeArhKd94Gq",
	"+6JbjMnCbZBf68IFvxTGoHJlXEPVJpGDexv3h8P5w/mR5rwt7E8sma3WlhRqexVKqA7Jo3UI3+4Os72s",
	"H7qm+0vmgRSoXD82mKBygksLeBfPuUqxfg3rO90vv/rqTGuDC0LdrJ6vYy+uvgStbzfhzcXFGbzkVsR+",
	"FnqNx4NxOXXtX9x6QcxRMg5fphgbdDs7A3ivqnoFHJ71w8Wo4wld2HWTOIDw9oquP+OxJz6iKeoCZHhd",
	"hd6rpeKZfvUSZuIOk/5CqEQvINYF7dx5AU/3fq2LDFTm5kY7JzF5sNb/vvt2L7sIUaB7t+EZOs82H7dj",
	"UXNRPR79h70yqN4e1u8v5dtDw8Gtdr9OUplQp6hSIoHdUZtXPv1AHNb/eukAxtsyplUvRr1WQOVPuIy+",
	"FdYXSm0g45KoDZN2fH4iSfj3GajSgPSquod6RkCvHL0Koztew71ff7yG53VQ+Uer+Kassj/rAaH6n6X8",
	"Y6eHg3QAs/tfFXYevKAcllRotwmujk//BNP4k5Au6N9TjOuvsWUVphe2TpI4MzopYvoBYRGLWGFk+bpq",
	"x8Mhz8WApA4W2shkyFbRtoxTHXMJCd52iRgPh5Lm59o6+mdwd8hWn1b/GQBdrz12Ph0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
