//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	IcaaBearerAuthScopes        = "icaaBearerAuth.Scopes"
	IcaaCookieAuthScopes        = "icaaCookieAuth.Scopes"
	IcaaRefreshCookieAuthScopes = "icaaRefreshCookieAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	AuthError            ErrorCode = "AuthError"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
)

// Defines values for UserInfoRoles.
const (
	ADMIN UserInfoRoles = "ADMIN"
)

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// IsAdmin Deprecated - use roles array instead. True if user has ADMIN role.
	IsAdmin       bool   `json:"isAdmin"`
	ProfilePicURL string `json:"profilePicURL"`

	// Roles User's assigned roles
	Roles     []UserInfoRoles `json:"roles"`
	UserEmail string          `json:"userEmail"`
}

// UserInfoRoles defines model for UserInfo.Roles.
type UserInfoRoles string

// PostLoginGoogleJSONBody defines parameters for PostLoginGoogle.
type PostLoginGoogleJSONBody struct {
	GoogleJWT string `json:"googleJWT"`
}

// PostLoginGoogleJSONRequestBody defines body for PostLoginGoogle for application/json ContentType.
type PostLoginGoogleJSONRequestBody PostLoginGoogleJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Logs the user out (deprecated, use DELETE /login/session)
	// (DELETE /login/google)
	DeleteLoginGoogle(w http.ResponseWriter, r *http.Request)
	// Logs in and returns the auth cookie
	// (POST /login/google)
	PostLoginGoogle(w http.ResponseWriter, r *http.Request)
	// Returns info about the logged in user (deprecated, use GET /login/session)
	// (GET /login/google/userInfo)
	GetLoginGoogleUserInfo(w http.ResponseWriter, r *http.Request)
	// Refreshes the access token using a refresh token
	// (POST /login/refresh)
	PostLoginRefresh(w http.ResponseWriter, r *http.Request)
	// Logs the user out
	// (DELETE /login/session)
	DeleteLoginSession(w http.ResponseWriter, r *http.Request)
	// Returns info about the current session/user
	// (GET /login/session)
	GetLoginSession(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteLoginGoogle operation middleware
func (siw *ServerInterfaceWrapper) DeleteLoginGoogle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLoginGoogle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLoginGoogle operation middleware
func (siw *ServerInterfaceWrapper) PostLoginGoogle(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLoginGoogle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLoginGoogleUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetLoginGoogleUserInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLoginGoogleUserInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLoginRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostLoginRefresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaRefreshCookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLoginRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLoginSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteLoginSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLoginSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLoginSession operation middleware
func (siw *ServerInterfaceWrapper) GetLoginSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLoginSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("DELETE "+options.BaseURL+"/login/google", wrapper.DeleteLoginGoogle)
	m.HandleFunc("POST "+options.BaseURL+"/login/google", wrapper.PostLoginGoogle)
	m.HandleFunc("GET "+options.BaseURL+"/login/google/userInfo", wrapper.GetLoginGoogleUserInfo)
	m.HandleFunc("POST "+options.BaseURL+"/login/refresh", wrapper.PostLoginRefresh)
	m.HandleFunc("DELETE "+options.BaseURL+"/login/session", wrapper.DeleteLoginSession)
	m.HandleFunc("GET "+options.BaseURL+"/login/session", wrapper.GetLoginSession)

	return m
}

type DeleteLoginGoogleRequestObject struct {
}

type DeleteLoginGoogleResponseObject interface {
	VisitDeleteLoginGoogleResponse(w http.ResponseWriter) error
}

type DeleteLoginGoogle200ResponseHeaders struct {
	SetCookie []string
}

type DeleteLoginGoogle200Response struct {
	Headers DeleteLoginGoogle200ResponseHeaders
}

func (response DeleteLoginGoogle200Response) VisitDeleteLoginGoogleResponse(w http.ResponseWriter) error {

	for _, cookie := range response.Headers.SetCookie {
		w.Header().Add("Set-Cookie", cookie)
	}

	w.WriteHeader(200)
	return nil
}

type PostLoginGoogleRequestObject struct {
	Body *PostLoginGoogleJSONRequestBody
}

type PostLoginGoogleResponseObject interface {
	VisitPostLoginGoogleResponse(w http.ResponseWriter) error
}

type PostLoginGoogle200ResponseHeaders struct {
	SetCookie []string
}

type PostLoginGoogle200JSONResponse struct {
	Body    UserInfo
	Headers PostLoginGoogle200ResponseHeaders
}

func (response PostLoginGoogle200JSONResponse) VisitPostLoginGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	for _, cookie := range response.Headers.SetCookie {
		w.Header().Add("Set-Cookie", cookie)
	}

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostLoginGoogle401JSONResponse Error

func (response PostLoginGoogle401JSONResponse) VisitPostLoginGoogleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetLoginGoogleUserInfoRequestObject struct {
}

type GetLoginGoogleUserInfoResponseObject interface {
	VisitGetLoginGoogleUserInfoResponse(w http.ResponseWriter) error
}

type GetLoginGoogleUserInfo200JSONResponse UserInfo

func (response GetLoginGoogleUserInfo200JSONResponse) VisitGetLoginGoogleUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLoginGoogleUserInfo401JSONResponse Error

func (response GetLoginGoogleUserInfo401JSONResponse) VisitGetLoginGoogleUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginRefreshRequestObject struct {
}

type PostLoginRefreshResponseObject interface {
	VisitPostLoginRefreshResponse(w http.ResponseWriter) error
}

type PostLoginRefresh200ResponseHeaders struct {
	SetCookie []string
}

type PostLoginRefresh200JSONResponse struct {
	Body    UserInfo
	Headers PostLoginRefresh200ResponseHeaders
}

func (response PostLoginRefresh200JSONResponse) VisitPostLoginRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	for _, cookie := range response.Headers.SetCookie {
		w.Header().Add("Set-Cookie", cookie)
	}

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostLoginRefresh401JSONResponse Error

func (response PostLoginRefresh401JSONResponse) VisitPostLoginRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteLoginSessionRequestObject struct {
}

type DeleteLoginSessionResponseObject interface {
	VisitDeleteLoginSessionResponse(w http.ResponseWriter) error
}

type DeleteLoginSession200ResponseHeaders struct {
	SetCookie []string
}

type DeleteLoginSession200Response struct {
	Headers DeleteLoginSession200ResponseHeaders
}

func (response DeleteLoginSession200Response) VisitDeleteLoginSessionResponse(w http.ResponseWriter) error {

	for _, cookie := range response.Headers.SetCookie {
		w.Header().Add("Set-Cookie", cookie)
	}

	w.WriteHeader(200)
	return nil
}

type GetLoginSessionRequestObject struct {
}

type GetLoginSessionResponseObject interface {
	VisitGetLoginSessionResponse(w http.ResponseWriter) error
}

type GetLoginSession200JSONResponse UserInfo

func (response GetLoginSession200JSONResponse) VisitGetLoginSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLoginSession401JSONResponse Error

func (response GetLoginSession401JSONResponse) VisitGetLoginSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")

	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Logs the user out (deprecated, use DELETE /login/session)
	// (DELETE /login/google)
	DeleteLoginGoogle(ctx context.Context, request DeleteLoginGoogleRequestObject) (DeleteLoginGoogleResponseObject, error)
	// Logs in and returns the auth cookie
	// (POST /login/google)
	PostLoginGoogle(ctx context.Context, request PostLoginGoogleRequestObject) (PostLoginGoogleResponseObject, error)
	// Returns info about the logged in user (deprecated, use GET /login/session)
	// (GET /login/google/userInfo)
	GetLoginGoogleUserInfo(ctx context.Context, request GetLoginGoogleUserInfoRequestObject) (GetLoginGoogleUserInfoResponseObject, error)
	// Refreshes the access token using a refresh token
	// (POST /login/refresh)
	PostLoginRefresh(ctx context.Context, request PostLoginRefreshRequestObject) (PostLoginRefreshResponseObject, error)
	// Logs the user out
	// (DELETE /login/session)
	DeleteLoginSession(ctx context.Context, request DeleteLoginSessionRequestObject) (DeleteLoginSessionResponseObject, error)
	// Returns info about the current session/user
	// (GET /login/session)
	GetLoginSession(ctx context.Context, request GetLoginSessionRequestObject) (GetLoginSessionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteLoginGoogle operation middleware
func (sh *strictHandler) DeleteLoginGoogle(w http.ResponseWriter, r *http.Request) {
	var request DeleteLoginGoogleRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteLoginGoogle(ctx, request.(DeleteLoginGoogleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteLoginGoogle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteLoginGoogleResponseObject); ok {
		if err := validResponse.VisitDeleteLoginGoogleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLoginGoogle operation middleware
func (sh *strictHandler) PostLoginGoogle(w http.ResponseWriter, r *http.Request) {
	var request PostLoginGoogleRequestObject

	var body PostLoginGoogleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLoginGoogle(ctx, request.(PostLoginGoogleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLoginGoogle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLoginGoogleResponseObject); ok {
		if err := validResponse.VisitPostLoginGoogleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLoginGoogleUserInfo operation middleware
func (sh *strictHandler) GetLoginGoogleUserInfo(w http.ResponseWriter, r *http.Request) {
	var request GetLoginGoogleUserInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLoginGoogleUserInfo(ctx, request.(GetLoginGoogleUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLoginGoogleUserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLoginGoogleUserInfoResponseObject); ok {
		if err := validResponse.VisitGetLoginGoogleUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLoginRefresh operation middleware
func (sh *strictHandler) PostLoginRefresh(w http.ResponseWriter, r *http.Request) {
	var request PostLoginRefreshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLoginRefresh(ctx, request.(PostLoginRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLoginRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLoginRefreshResponseObject); ok {
		if err := validResponse.VisitPostLoginRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteLoginSession operation middleware
func (sh *strictHandler) DeleteLoginSession(w http.ResponseWriter, r *http.Request) {
	var request DeleteLoginSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteLoginSession(ctx, request.(DeleteLoginSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteLoginSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteLoginSessionResponseObject); ok {
		if err := validResponse.VisitDeleteLoginSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLoginSession operation middleware
func (sh *strictHandler) GetLoginSession(w http.ResponseWriter, r *http.Request) {
	var request GetLoginSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLoginSession(ctx, request.(GetLoginSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLoginSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLoginSessionResponseObject); ok {
		if err := validResponse.VisitGetLoginSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYXW/TSBf+K0fzvtLSyo3DsldGXIQSIFCgatPlolTt1D6JB5wZMzNum0X576szM46d",
	"2JQsrIRW4ir+mPP9nOcc5wtL1aJUEqU1LPnCTJrjgrvLsdZK00WpVYnaCnSPU5Uh/f5f44wl7H9xoyAO",
	"0rETPaSDq4gt0Bg+dzJ4xxdlgSxhIwmVxLsSU4sZIJ0HlaaV1pgNWMTssqRjxmoh52y1ipjGz5XQmLHk",
	"3PvQaL5Yn1fXHzG1ZLVxgezKakFyE2lRS1740CI2qmxeX09kWdk/eSEyboWS/vFFx5OInRnUEzlT3dTg",
	"XSk0mpGlm5nSC25ZwjJu8cCKBbIeZcKMsoWQJJChSbUoyThL2DMsNaacsnMAlUHQqkADXGu+BCGNRZ4N",
	"YKorBDGjAxpybmD07M3krTvbyuK1UgVySfZKrWaiwGORnp0ckdWOR85O1x+K+jcD3Bgxl5h5d1jEhMWF",
	"aefYedCbuPDAhUD35PR4wUXR48dWwes0bQcQtXLeVliH0UXGKmIG00oLuzwltPpYRcr5U+QaNUGCnly7",
	"u+d1EV+9n7JoKyWTw9EIeJqiMWDVJ5QgJJC80uIvByLIkWdI6HKd4Wrh9Da1ya0tHRBSzg+V+iSw9uBb",
	"xlJ3mkpA79d3kjs7dP5ydHg4Pj29nL57PX7bmOSleI3L2ugJzjSa/Ju2tT+3YRwezJQOT+r3KLNSCWn3",
	"7vXsZPz8ZHz68muuUZlE6LFNX0YSRscTILuFms+FnIOQVgFpdZAXtqitwJGaO9DcoDZe/OFgOBhS6KpE",
	"yUvBEvbIPYpYyW3uwBAXJBbPlZoX6D0o0IaruitZYnWF25DY32/6NtnfhzOD8Gx8NJ6OIWg1aMiVdQt/",
	"kM+VrtN5zQ1mwCubR+CNGrA5htcmApzNMLXiBovlOnw64PpfVXbwgcIlTnL4m2SOSUiRS8ULHxL1limV",
	"NB78vw+H/f3uTGBGilnEPJadxCnaAw+YruAUi8J7fa3VLWmxKgTTjmVQNwXfHAwd3D55DMfc5k/ix/CG",
	"3x2M5vhk+DiCLop6D/aMklWbA1hy/qXTe+cXq4uImWqx4HrJEnak5mYjzfCgAULk2Lm3yHuOcZVx82Cz",
	"KMfK2O2SfK7Q2KcqW/oxKy1KJ8nLshCpk40/GiWbOd0dQR60xFbf5NTmaA9LrraRPc0RvK/w6v2Ualoo",
	"aj24FTZnbc3UF6t+iO0c1H3LxXr+9nhJ9QNTOZqcVcUAyO3AmlxmmyRG0xRBo600TTRRs5oBYqoMrjpY",
	"vHJKrrrYu/KNt2uL5Aiez8ndNqH+g7b4UA2Hj1If26XT4Z5g0wUvrS3fyWLZ2yxePOTjfvneHorYH8OH",
	"/1pN/bbVU9AzycNApb1wq3O7TSpkKDPV1Pesy3GYQSS/we5x1Vrm5mi/l+NfjKdfJ/iT4A0NNODXxB/k",
	"WCBXIR2t9DH3C2xzxBr3P6m33ERwQ/knFn9d7p2S2uXpbqH22qgI/eB4NfB2JwkeVr3rkFUwR0klROAg",
	"8XZjY/NspIotGgJBUdz4Lw8a/zILwkqie2lMhRk8CHuWsi7Je32IWY+VsNX9LKxMN1bChpB358i3TfI6",
	"xP29ZCnx9vIHCZNU/KdIEw5qcIHS4L+WttLJeheinu+C7b0oHAkdsfFxUhlaTXmPoc3u216v22HsvhgH",
	"iNyoT33ducPafN/SfBo8/bU1/+DWTHNjPWPbwbe5nL63aXw2lO7+FJI2lK41Mb86L++v2K9B2coqhD50",
	"ixDbqchR9++SUHrUNw7q59sFPtYqq1JXV3+IRazSRfj7wyRxzEsxIK2DW6WLLGZkZVPHkUp5ARne9KlI",
	"4rig97kyNnk0HD6M2epi9XcAAAD//7uuYwHdFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
